# .github/workflows/deploy.yml
name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - shahtimes # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy files to VPS via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "."
          target: "/home/deploy/app"

      - name: Deploy app via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/deploy/app

            cat <<EOF > .env
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            EOF


            docker stop epaper || true && docker rm epaper || true
            docker build -t epaper .
            docker run -d --name epaper --restart unless-stopped -p 3000:3000 \
            -v /home/deploy/media:/app/public/media \
            # -v /home/deploy/tmp:/tmp \
            epaper
            docker network connect postgres_default epaper
